set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property PACKAGE_PIN Y9 [get_ports SYS_CLK_OG]
set_property PACKAGE_PIN W22 [get_ports LED_DRIVE_1]
set_property PACKAGE_PIN H18 [get_ports SWITCH_1]
set_property PACKAGE_PIN U19 [get_ports LED_DRIVE_2]
set_property PACKAGE_PIN H17 [get_ports SWITCH_2]
set_property PACKAGE_PIN M15 [get_ports RESET]
set_property PACKAGE_PIN V8 [get_ports o_HEADER_DRIVE_1]
set_property PACKAGE_PIN W8 [get_ports o_HEADER_DRIVE_2]
set_property IOSTANDARD LVCMOS33 [get_ports o_HEADER_DRIVE_1]
set_property IOSTANDARD LVCMOS33 [get_ports o_HEADER_DRIVE_2]
set_property IOSTANDARD LVCMOS33 [get_ports SYS_CLK_OG]
set_property IOSTANDARD LVCMOS33 [get_ports SWITCH_1]
set_property IOSTANDARD LVCMOS33 [get_ports LED_DRIVE_1]
set_property IOSTANDARD LVCMOS33 [get_ports SWITCH_2]
set_property IOSTANDARD LVCMOS33 [get_ports LED_DRIVE_2]
set_property IOSTANDARD LVCMOS33 [get_ports RESET]
